name: Labeler
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - name: Validate JSON
      uses: OrRosenblatt/validate-json-action@0.1.0
      with:
        schema: ./schema.json
        json: ./plugins.json
